services:
  - type: web
    name: cropsmart-crop-price-app
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    autoDeploy: true
